name: sudoku
description: A fully fledged Sudoku game.


version: 2.4.1+2041

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Sudoku Logic
  sudoku_solver_generator: ^2.1.0+1

  # Saving Preferences Locally
  shared_preferences: ^2.0.15

  # Animated Alert Dialogs
  flutter_animated_dialog: ^2.0.1

  # Splashscreen 1.4.0
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: a05b64f8326f7c2615491e9f47a1f2dcf8b28a69

  # Hyperlinks
  url_launcher: ^6.1.4

  # Windows Title Bar
  bitsdojo_window: ^0.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

  # Native Splashscreen
  flutter_native_splash: ^2.2.3+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/icon/icon_foreground.png
    - assets/icon/icon_round.png

  